### ISSUE TITLE
The "Run Zephyr Installer" step fails in Mac OSX

### ISSUE THREAD

**Issue by belenbarrospena** [todorez/crops#11] opened 2016-03-04 11:05 UTC
I was following the instructions at https://github.com/todorez/crops/wiki

After downloading an installing the Docker Toolbox for Mac, I opened the Docker Quickstart Terminal and typed 

source <(curl -s https://raw.githubusercontent.com/todorez/crops/master/installers/zephyr-installer.sh)

The terminal printed 

(23) Failed writing body

and did nothing else. See attached sceenshot

![failed-writing-body](https://cloud.githubusercontent.com/assets/684113/13525431/c6e9bbc2-e1f8-11e5-8e99-400878eda071.png)

Sourcing a local version of the zephyr-installer.sh script worked. 

My OSX version is 10.10.5

**Comment by todorez** [comment] 2016-03-04 15:23
@belenbarrospena were you on the VPN or internal network when you ran 

`source <(curl -s https://raw.githubusercontent.com/todorez/crops/master/installers/zephyr-installer.sh)` ?

**Comment by belenbarrospena** [comment] 2016-03-04 15:40
I was the first time I tried. Then I disconnected and tried the command several times. The last time was right before sourcing the local version of the script, which downloaded everything without problems. I can give it another try if that helps.

**Comment by todorez** [comment] 2016-03-04 16:04
@belenbarrospena  If you were able to run the installer after downloading it then networking connectivity is not the issue.
I think I can see what the problem is.. "source" on Mac OS X will occasionally close the pipe before it has received the whole input from curl. curl then complains with "Failed writing body".  Could you please try if the command below works for you? I have also updated the wiki.

`curl -O -s https://raw.githubusercontent.com/todorez/crops/master/installers/zephyr-installer.sh && source ./zephyr-installer.sh`

**Comment by belenbarrospena** [comment] 2016-03-04 17:26
Yep: that works. Happily downloading the codi image. Thanks!

**Comment by todorez** [comment] 2016-03-04 20:56
OK, I settled with 

`curl -kOs https://raw.githubusercontent.com/todorez/crops/master/installers/zephyr-installer.sh && source ./zephyr-installer.sh`

which works on Linux, WIndows and Mac OS X. Closing.

**Closed by todorez** 2016-03-04 20:56 UTC
